### ISSUE TITLE
Broken and not going to be fixed

### ISSUE THREAD

**Issue by micheleAlberto** [hackerlist/glassdoor#23]
I understand this project is not being updated or fixed and has some serious problem that makes it not functional at all. Please write it clearly in the readme.md , it seems a lot of people cloned the repo and expected it to be working.

**Comment by mekarpeles** [comment]
@micheleAlberto As perspective, for several years researchers were using the glassdoor tool to do analysis on the job industry. It's less necessary given they now provide an API for developers (which wasn't true at the time of authoring).

I do hope people do fork it and repair it -- I don't have the time or use case at the present (nor a good idea of which css selectors still work with their latest design).

Thanks for your comments, I've updated the README to reflect your points.
